ZO_CreateStringId("SI_PM_NAME", "|c99CCEFPostmaster|r")
ZO_CreateStringId("SI_PM_AND", " und ") 
ZO_CreateStringId("SI_PM_VERBOSE", "Beuteverlauf im Chatfenster")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "Alle entnommen Gegenstände werden im Chatfenster angezeigt.")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "Nur Systemnachrichten: |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "Wenn diese Option aktiviert ist, wird beim Klicken von |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r nur Anhänge entnommen, wenn es sich um eine Handwerk- oder Gildenladennachricht handelt. Nachrichten von anderen Spielern bleiben im Posteingang.")
ZO_CreateStringId("SI_PM_SKIPCOD", "Nachnahme: |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r überspringt "..GetString(SI_MAIL_SEND_COD).."")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "Wenn diese Option aktiviert ist, werden bei |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r "..GetString(SI_MAIL_SEND_COD).." Nachrichten ignoriert")
ZO_CreateStringId("SI_PM_HELP_01", "Um "..GetString(SI_PM_NAME).." zu nutzen, öffnest du deinen Posteingang.")
ZO_CreateStringId("SI_PM_HELP_02", "Mit der Taste |cFF00FF"..GetString(SI_LOOT_TAKE).."|r wird bei der ausgewählten Nachricht alle Anhänge entnommen und die Nachricht anschliessend gelöscht.")
ZO_CreateStringId("SI_PM_HELP_03", "Mit der Taste |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r werden die Anhänge aller Nachrichten entnommen und die Nachrichten anschliessend gelöscht.")
ZO_CreateStringId("SI_PM_HELP_04", "Verwende im Chatfenster den Slash-Befehl |cFF00FF/pm|r oder |cFF00FF/postmaster|r um in diese Einstellungen zu gelangen.")
