ZO_CreateStringId("SI_PM_NAME", "|c99CCEFPostmaster|r")
ZO_CreateStringId("SI_PM_AND", " and ") 
ZO_CreateStringId("SI_PM_VERBOSE", "Loot Messages in Chat")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "Sends verbose messages to chat when mail attachments are retrieved")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r Skips Other Player Mail")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "When enabled, the |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r command will only collect system mails such as hireling and guild store transactions, leaving direct mail from other players in your mailbox")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r Skips "..GetString(SI_MAIL_SEND_COD).." Mail")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "When this option is enabled, the |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r command will not collect "..GetString(SI_MAIL_SEND_COD).." mail")
ZO_CreateStringId("SI_PM_HELP_01", "To interact with "..GetString(SI_PM_NAME)..", open your mail inbox")
ZO_CreateStringId("SI_PM_HELP_02", "The |cFF00FF"..GetString(SI_LOOT_TAKE).."|r button will Loot and Delete the |cEFEBBEcurrently selected|r mail")
ZO_CreateStringId("SI_PM_HELP_03", "The |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r button will Loot and Delete |cEFEBBEall|r mails in your inbox that have attachments, according to the options below")
ZO_CreateStringId("SI_PM_HELP_04", "Use the |cFF00FF/pm|r or |cFF00FF/postmaster|r commands in the chat window as a shortcut to this options screen")