ZO_CreateStringId("SI_PM_NAME", "|c99CCEFReceveur des postes|r")
ZO_CreateStringId("SI_PM_AND", " et ") 
ZO_CreateStringId("SI_PM_VERBOSE", "Butin messages dans le chat")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "Envoie des messages verbeux discuter lorsque les pièces jointes sont prises")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r exclut courrier vide du système")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne prendra pas le courrier du système qui ne dispose pas d' une pièce jointe, telles que les notifications pour les éléments ajoutés aux collections . Désactiver pour supprimer ce type de courrier à la place .")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r exclut le courrier d'autres joueurs")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "Lorsque cette option est activée , la commande "..GetString(SI_LOOT_TAKE_ALL).." ne traiter le courrier à partir du système - comme le courrier des fournisseurs et des ventes de la boutique de guilde - permettant au courrier d'autres joueurs à rester dans la courrier reçu")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r exclut courrier "..GetString(SI_MAIL_SEND_COD))
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne sera pas collecter le courrier "..GetString(SI_MAIL_SEND_COD))
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r exclut courrier vide d'autres joueurs")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne prendra pas les messages d'autres joueurs qui ne disposent pas d'une pièce jointe . Désactiver pour supprimer ce type de courrier à la place .")
ZO_CreateStringId("SI_PM_HELP_01", "Pour interagir avec "..GetString(SI_PM_NAME).." , ouvrez votre courrier reçu")
ZO_CreateStringId("SI_PM_HELP_02", "Le |cFF00FF"..GetString(SI_LOOT_TAKE).."|r bouton va prendre les pièces jointes de et supprimer le message actuellement sélectionné")
ZO_CreateStringId("SI_PM_HELP_03", "Le |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r bouton va prendre les pièces jointes à partir de et supprimer tous les messages dans courrier reçu")
ZO_CreateStringId("SI_PM_HELP_04", "Utilisez le |cFF00FF/pm|r ou |cFF00FF/postmaster|r commandes dans la fenêtre de chat comme un raccourci vers cet écran d'options")