ZO_CreateStringId("SI_PM_NAME", "|c99CCEFPostmaster|r")
ZO_CreateStringId("SI_PM_AND", " et ") 
ZO_CreateStringId("SI_PM_VERBOSE", "Message de réception dans le chat")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "Envoi un message dans le chat lors de la récupération des pièces jointes (mail)")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r : Exclure les courriers vides du système")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne traitera pas le courrier système qui ne dispose pas d'une pièce jointe, telles que les notifications pour les objets ajoutés aux collections . Désactiver pour supprimer ce type de courrier.")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r : Exclure le courrier des joueurs")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "Lorsque cette option est activée , la commande "..GetString(SI_LOOT_TAKE_ALL).." ne traitera que le courrier système - courrier des fournisseurs et ventes de la boutique de guilde - et laissera le courrier des joueurs dans votre boite mail")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r : Exclure le  courrier "..GetString(SI_MAIL_SEND_COD))
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne récupérera pas le courrier "..GetString(SI_MAIL_SEND_COD))
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r : Exclure le courrier vide des joueurs")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL_TOOLTIP", "Lorsque cette option est activée , la commande |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r ne traitera pas les messages des joueurs ne possédant pas de pièce jointe. Désactiver pour supprimer ce type de courrier.")
ZO_CreateStringId("SI_PM_HELP_01", "Pour interagir avec "..GetString(SI_PM_NAME).." , ouvrez votre courrier reçu")
ZO_CreateStringId("SI_PM_HELP_02", "Le bouton |cFF00FF"..GetString(SI_LOOT_TAKE).."|r prélévera les pièces jointes du message puis le supprimera.")
ZO_CreateStringId("SI_PM_HELP_03", "Le bouton |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r prélévera les pièces jointes de tous les messages puis les supprimera.")
ZO_CreateStringId("SI_PM_HELP_04", "Utilisez les commandes |cFF00FF/pm|r ou |cFF00FF/postmaster|r dans la fenêtre de chat comme un raccourci vers cet écran d'options")
