ZO_CreateStringId("SI_PM_NAME", "|c99CCEF郵便局長|r") 
ZO_CreateStringId("SI_PM_AND", " と ") 
ZO_CreateStringId("SI_PM_VERBOSE", "チャットのメッセージを略奪")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "メールの添付ファイルを取得するときにチャットに詳細メッセージを送信")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは、他のプレイヤーからのメッセージをスキップ")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "このオプションを有効にすると、メールボックス内の他のプレーヤーからのダイレクトメールを残して、そのような雇い人やギルドストア取引などのシステムからのみ収集したメッセージにコマンドを|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rが発生します")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは"..GetString(SI_MAIL_SEND_COD).."のメールをスキップ")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "このオプションを有効にすると、コマンド|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは"..GetString(SI_MAIL_SEND_COD).."のメッセージを取ることはありません")
ZO_CreateStringId("SI_PM_HELP_01", GetString(SI_PM_NAME).."と相互作用するように、メールの受信トレイを開きます")
ZO_CreateStringId("SI_PM_HELP_02", "|cFF00FF"..GetString(SI_LOOT_TAKE).."|rボタンを押してから、電子メールの添付ファイルを削除して、現在選択されているメッセージを削除します")
ZO_CreateStringId("SI_PM_HELP_03", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rボタンは、電子メールの添付ファイルを持って受信トレイ内のすべてのメッセージをからの電子メールの添付ファイルを削除し、削除します")
ZO_CreateStringId("SI_PM_HELP_04", "このオプション画面へのショートカットとしてチャットウィンドウに|cFF00FF/pm|rと|cFF00FF/postmaster|rのコマンドを使用します")