ZO_CreateStringId("SI_PM_NAME", "|c99CCEFPostmaster|r")
ZO_CreateStringId("SI_PM_AND", " と ") 
ZO_CreateStringId("SI_PM_VERBOSE", "チャットに取得メッセージ")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "メールに添付されたアイテムを取得時、詳細なメッセージをチャットに送ります。")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r添付ファイルのないシステムメールをスキップ")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL_TOOLTIP", "このオプションが有効化されている場合、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドはアイテムがコレクションに追加されたなどの通知のような、添付ファイルのないシステムメールをスキップします。逆に無効化することでそれらのメールを削除します。")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r 他プレイヤーのメールをスキップ")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "有効化時、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドはメールボックスにある雇ったサポートからのメールや、ギルドストアの取引などのシステムメールのみ取得し、他のプレイヤーからのダイレクトメールは取得しません。")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r"..GetString(SI_MAIL_SEND_COD).."メールをスキップ")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "このオプションが有効化されている場合、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r コマンドは"..GetString(SI_MAIL_SEND_COD).."メールを取得しません。")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r添付ファイルのない他プレイヤーのメールをスキップ")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL_TOOLTIP", "このオプションが有効化されている場合、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは添付ファイルのない他プレイヤーからのメールをスキップします。逆に無効化することでメールを削除します。")
ZO_CreateStringId("SI_PM_HELP_01", GetString(SI_PM_NAME).."とインタラクトするには、メールインボックスを開いてください。")
ZO_CreateStringId("SI_PM_HELP_02", "|cFF00FF"..GetString(SI_LOOT_TAKE).."|rボタンは、|cEFEBBE現在選択されている|rメールを取得し、削除します。")
ZO_CreateStringId("SI_PM_HELP_03", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rボタンは下記オプションと合致したインボックスにある|cEFEBBE全ての|rメールを取得し、削除します。")
ZO_CreateStringId("SI_PM_HELP_04", "|cFF00FF/pm|rか|cFF00FF/postmaster|rコマンドはチャットウィンドウで使用することにより、このオプション画面へのショートカットとして使用できます。")