ZO_CreateStringId("SI_PM_NAME", "|c99CCEF郵便局長|r") 
ZO_CreateStringId("SI_PM_AND", " と ") 
ZO_CreateStringId("SI_PM_VERBOSE", "チャットのメッセージを略奪")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "メールの添付ファイルを取得するときにチャットに詳細メッセージを送信")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは、システムからのメールを除外する")
ZO_CreateStringId("SI_PM_SKIPEMPTYSYSMAIL_TOOLTIP", "このオプションを有効にすると、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは、このようなコレクションに追加された項目のための通知として、添付ファイルを持っていないシステムからのメールを取ることはありません。代わりに、このようなメールを削除するには、無効にします。")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは他のプレイヤーからのメールを除外します")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "このオプションを有効にすると、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは、このような雇い人やギルドストア取引などのシステムからのメールを、かかります。他のプレイヤーからの直接メールがあなたのメールボックスに残されます")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは"..GetString(SI_MAIL_SEND_COD).."を除外します")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "このオプションを有効にすると、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは、任意の"..GetString(SI_MAIL_SEND_COD).."のメールを取ることはありません")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rは他のプレイヤーから空メールを除外します")
ZO_CreateStringId("SI_PM_SKIPEMPTYPLAYERMAIL_TOOLTIP", "このオプションを有効にすると、|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rコマンドは、添付ファイルを持っていない他のプレイヤーからのすべてのメールを取ることはありません。代わりに、このようなメールを削除するには、無効にします。")
ZO_CreateStringId("SI_PM_HELP_01", GetString(SI_PM_NAME).."と相互作用するように、メールの受信トレイを開きます")
ZO_CreateStringId("SI_PM_HELP_02", "|cFF00FF"..GetString(SI_LOOT_TAKE).."|rボタンを押してから、電子メールの添付ファイルを削除して、現在選択されているメッセージを削除します")
ZO_CreateStringId("SI_PM_HELP_03", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|rボタンを押して、以下のオプションに従って取り、あなたの受信トレイ内のすべてのメールを削除します")
ZO_CreateStringId("SI_PM_HELP_04", "このオプション画面へのショートカットとしてチャットウィンドウに|cFF00FF/pm|rと|cFF00FF/postmaster|rのコマンドを使用します")