ZO_CreateStringId("SI_PM_NAME", "|c99CCEFпочтмейстер|r")
ZO_CreateStringId("SI_PM_AND", " и ") 
ZO_CreateStringId("SI_PM_VERBOSE", "Лут сообщения в чат")
ZO_CreateStringId("SI_PM_VERBOSE_TOOLTIP", "Посылает многословные сообщения в чат , когда вложения электронной почты извлекаются")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r Пропускает почту от других игроков")
ZO_CreateStringId("SI_PM_SKIPPLAYERMAIL_TOOLTIP", "Когда эта опция включена , то команда |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r будет собирать только вложения электронной почты из почты, отправляемой из системы - такие, как посланные наймитов и продаж магазина - что позволяет прямой почтовой рассылки от других игроков, чтобы остаться в вашем почтовом ящике")
ZO_CreateStringId("SI_PM_SKIPCOD", "|cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r пропускает "..GetString(SI_MAIL_SEND_COD).." почту")
ZO_CreateStringId("SI_PM_SKIPCOD_TOOLTIP", "Если эта опция включена , то команда |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r не будет принимать "..GetString(SI_MAIL_SEND_COD).." сообщения")
ZO_CreateStringId("SI_PM_HELP_01", "Для того, чтобы взаимодействовать с "..GetString(SI_PM_NAME).." , открыть свой ​​почтовый ящик")
ZO_CreateStringId("SI_PM_HELP_02", "Кнопка |cFF00FF"..GetString(SI_LOOT_TAKE).."|r будет удалять вложения электронной почты из и удаления выбранной в данный момент сообщение")
ZO_CreateStringId("SI_PM_HELP_03", "Кнопка |cFF00FF"..GetString(SI_LOOT_TAKE_ALL).."|r будет удалять вложения электронной почты из и удалять все сообщения в почтовом ящике , которые имеют вложения")
ZO_CreateStringId("SI_PM_HELP_04", "Используйте |cFF00FF/pm|r или команды |cFF00FF/postmaster|r в окне чата в качестве ярлыка для этого экрана опций")
